// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAakbBjiQyYQYlRvjfEL_uzEbXsGtUzA0A',
    appId: '1:500636963778:web:9c20d3cd9aa99494483c5b',
    messagingSenderId: '500636963778',
    projectId: 'chat-app-c3319',
    authDomain: 'chat-app-c3319.firebaseapp.com',
    storageBucket: 'chat-app-c3319.appspot.com',
    measurementId: 'G-R1Z2JCSMGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOwe4z4lPve9KAsiPe7UpK4gIwqRpLBcw',
    appId: '1:500636963778:android:4f48501cce1e0a71483c5b',
    messagingSenderId: '500636963778',
    projectId: 'chat-app-c3319',
    storageBucket: 'chat-app-c3319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRzey_W0OX4lMn2GC6A9YRystc2QoWCXs',
    appId: '1:500636963778:ios:9fb26a92909863ad483c5b',
    messagingSenderId: '500636963778',
    projectId: 'chat-app-c3319',
    storageBucket: 'chat-app-c3319.appspot.com',
    iosClientId: '500636963778-cqtjs3h5gmmm01mi727grlp48lcok19v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
